name: ism_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-239.0.dev

dependencies:
  adaptive_theme: ^3.6.0
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  hexcolor: ^3.0.1
  http: ^1.2.2
  intl: ^0.19.0
  styled_widget: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
